# Generated by Django 4.2.7 on 2024-05-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_seller_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='Address',
            new_name='address',
        ),
    ]
