# Generated by Django 4.2.7 on 2024-05-05 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_category_order_product_remove_cart_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
