# Generated by Django 4.2.7 on 2024-05-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_cartitems_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_reference',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=20),
        ),
    ]
