# Generated by Django 4.2.7 on 2024-05-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_profile_uid_profile_id_profile_my_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='my_date_field',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
