# Generated by Django 4.2.7 on 2024-04-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_color_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizevariant',
            name='image',
            field=models.ImageField(default=0, upload_to='product'),
            preserve_default=False,
        ),
    ]
