# Generated by Django 4.2.7 on 2024-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sizevariant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariant',
            name='image',
            field=models.ImageField(default=None, upload_to='product'),
        ),
    ]
